### ISSUE TITLE
DupCharToken API is shutting down infinite loop 

### ISSUE THREAD

**Issue by BWare96** [Roll20/roll20-api-scripts#868]
I am trying to use the DupCharToken to duplicate an Orc in the Storm Kings Thunder Module and the API keeps shutting down due to possible Infinite loop.

**Comment by shdwjk** [comment]
Can you give the call stack that was produced with the error?

**Comment by shdwjk** [comment]
Incidentally, it likely won't work on those tokens as their graphics are in the Marketplace, not a user library:

> Known bugs/issues:  If the avatar image of the character is not in a user library (i.e: it's a marketplace image or from the Monster Manual, or the like), 
> due to limits placed upon the API, it can't set an avatar image. You will have to do that yourself.

**Comment by BWare96** [comment]
How do I get the call stack that was produced?

Yes, I saw the note about the token, however when I copy the Orc on a new game with no module loaded it works fine and includes the token image.

**Comment by shdwjk** [comment]
Usually there is a callstack in red along with the error.  However, that doesn't always happen with the possible infinite loop detection.  The way that is detected is based on a watchdog event in the sandbox which is touched each time the script returns control to the sandbox.  If control is not returned after some period of time, the sandbox kills the scripts.

What command are you running when it stops working?  I'm guessing just `!dupCharToken` which does several findObj() calls wrapping createObj() calls.  Storm King's Thunder is a big Game, so those will probably be very expensive calls and cause the watchdog to trigger.  The only way around that is to rewrite the script to defer as much work as possible.  Even though that script is pretty short, it would take a while to do that task as it requires restructuring it into a much more asynchronous model of operation.

**Comment by BWare96** [comment]
No call stack with the error.

You are correct in what I am running. As for rewriting the script that is beyond the time I would have. I would first have to teach myself roll20 scripting. So I guess it is back to pen and paper for the big group encounters.

**Comment by shdwjk** [comment]
Is there a reason that copying the existing orc tokens multiple times, or dragging in new orc tokens is insufficient to your needs?

**Comment by BWare96** [comment]
When I just drag multiple Orcs to the map. When I reduced the HP from the token bar. It reduces all the tokens HPs.



On Oct 13, 2019 10:12 PM, "Aaron C. Meadows" <notifications@github.com> wrote:

Is there a reason that copying the existing orc tokens multiple times, or dragging in new orc tokens is insufficient to your needs?

**Comment by ChrisDDickey** [comment]
I am the Author of the script, and just noticed this issue had been opened (wish somebody had contacted me on Roll20 PM). 

Anyway, I have a few questions. 

BWare96:
Did this happen when you when you were just trying to duplicate one token, or were you trying to make a fairly large number of Orcs?
Because one quick work around is to break a large batch into smaller batches.
!dupCharToken 2           (will make Orc 1 and Orc 2)
!dupCharToken 2 3       (will make Orc 3 and Orc 4)
!DupcharToken 2 5        (will make Orc 5 and Orc 6)
etc.
I would be very interested in knowing how many duplication's it did / did not happen on. ie: it happens when trying to make more than X orcs, but never when trying to make less than Y orcs.
Also, I am unfamiliar with "Storm King's Thunder" and am curious as to what you too consider a "big" game. How many characters are in the module. How many Attributes and Abilities would an Orc have?

shwjdk:
What are your ideas for rewriting?
The one thing I notice is that the script makes the new characters one at a time. Thus for each newly created character it calls FindObj() looking for the original characters attributes and again looking for abilities.  Thus for 10 new characters it makes 20 calls to FindObj().  Obviously it should be fairly straightforward to create all the new characters, then after all have been created, make one call to FindObj() to get all the attributes, and then do 10 CreateObj()s, etc. 
However if the timeout is happening when just making one character, then this change would not save any time at all, it only saves time if making more than one character. 
I would appreciate any advice you have.

**Comment by ChrisDDickey** [comment]
OK, did testing on my own small campaign (just a few dozen characters, some with very few attributes). 
My old code worked when making 36 or fewer copies of a certain character, but always gave the infinite loop detected error whenever trying to make 37 copies or more. 
I pulled everything out of the one loop I talked about above that I could and the cutoff point improved slightly to somewhere between 42 and 45 copies. so there was a noticeable improvement, but not huge. 
Any other ideas or tricks you could suggest?

**Comment by ChrisDDickey** [comment]
OK, version 1.01 of DupCharToken went live yesterday, and like I said, there was some improvement, and I also updated the wiki page instructions to note that if this happens, to try making smaller batches. 

Unless anybody has any specific suggestions on how the script can be further improved, I think this issue should probably be closed, but I can't figure out how to close it myself, I assume the creator or the administrator will need to do that.

**Comment by BWare96** [comment]
Thank you Chris for the troubleshooting and tweaks to the code. Sorry it took so long to respond. It has been busy lately. I understand the limits and knowing what they are makes this a great tool. I will close the issue.

Brian
